version: '3.8'
services:
    app_server:
        build: application_server
        ports:
            - "8081:5000"
        volumes:
            - .:/app
        environment:
            FLASK_ENV: development

    web_server:
        build: web_server
        ports: 
            - "8080:8080"
        volumes:
            - ./web_server:/app
        stdin_open: true
        tty: true
        depends_on:
            - app_server
        environment:
            - CHOKIDAR_USEPOLLING=true
        